#!/usr/bin/env node
// Turns the Vite build in ./dist into a Swift source file that GoelCore can
// serve without a filesystem, a resource bundle, or a Bundle.module lookup —
// which is what makes the portal work identically in the macOS app bundle and
// in the statically linked Linux daemon.
//
// Run via `npm run build`. The output is committed; CI rebuilds and fails if it
// differs, so the checked-in Swift can never drift from the React source.

import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const portalDir = join(here, '..')
const repoRoot = join(portalDir, '..')

const DIST = join(portalDir, 'dist')
const OUT = join(repoRoot, 'Sources', 'GoelCore', 'Remote', 'Generated', 'PortalBundle.swift')

/**
 * Swift raw string literals are delimited by N `#` characters, and the literal
 * ends at the first `"""` followed by that many `#`. Interpolation is likewise
 * `\` + N `#` + `(`. Pick the smallest N for which neither sequence occurs in
 * the payload, so no escaping of the content itself is ever needed and the
 * bytes reach the browser exactly as Vite emitted them.
 *
 * A fixed N would be a latent bug: the day a bundle happens to contain `"""#`
 * inside a string constant, the Swift file would stop compiling — or worse,
 * compile with a truncated bundle.
 */
function rawLiteral(content) {
  let n = 1
  while (content.includes(`"""${'#'.repeat(n)}`) || content.includes(`\\${'#'.repeat(n)}(`)) {
    n++
    if (n > 16) throw new Error('could not find a safe raw-string delimiter')
  }
  const h = '#'.repeat(n)
  // The closing delimiter sits at column 0 deliberately. Swift strips from every
  // line whatever indentation the closing delimiter has, so any indentation here
  // would silently rewrite the payload.
  return `${h}"""\n${content}\n"""${h}`
}

/** Short content hash — long enough to never collide, short enough to read. */
function hash(content) {
  return createHash('sha256').update(content).digest('hex').slice(0, 16)
}

function read(path, hint) {
  try {
    return readFileSync(path, 'utf8')
  } catch {
    console.error(`error: ${path} is missing${hint ? ` — ${hint}` : ''}.`)
    process.exit(1)
  }
}

const built = (name) => read(join(DIST, name), 'run `npm run build` first')
const source = (...parts) => read(join(portalDir, 'src', ...parts))

const js = built('portal.js')
const css = built('portal.css')

// The login page is server-rendered and needs no React, but its CSS and JS are
// static — so they ship as assets too rather than as inline blocks, which is
// what lets the CSP forbid inline script and style outright.
//
// `themes.css` is concatenated here rather than duplicated in Swift: it is the
// one definition of the four palettes, shared by the portal bundle (via
// main.tsx) and by this page. Keeping a second copy in a Swift literal is
// exactly the drift this whole change exists to remove.
const loginCss = source('styles', 'themes.css') + '\n' + source('login', 'login.css')
const loginJs = source('login', 'login.js')

const jsHash = hash(js)
const cssHash = hash(css)
const loginCssHash = hash(loginCss)
const loginJsHash = hash(loginJs)

const swift = `// Generated by portal/scripts/codegen.mjs — DO NOT EDIT.
//
// The portal UI lives in /portal (React + TypeScript). Editing this file by
// hand puts the served bundle out of step with its source; the change would be
// erased by the next \`npm run build\` and CI would fail on the difference in
// the meantime.
//
// To change the portal:
//
//     cd portal && npm install && npm run build
//
// which rebuilds and regenerates this file. Commit both.

import Foundation

/// The compiled web portal, embedded as source so it needs no resource bundle
/// and behaves identically in the macOS app and the Linux daemon.
///
/// \`\`RemoteRouter\`\` serves these from \`/assets/<name>\` with a long-lived
/// immutable cache, which is safe precisely because the filename carries the
/// content hash: new bytes mean a new URL.
public enum PortalBundle {

    /// Content-addressed filenames. Changing the bundle changes the URL, so a
    /// stale cached copy can never be served against a new page shell.
    public static let jsName = "portal-${jsHash}.js"
    public static let cssName = "portal-${cssHash}.css"
    public static let loginJSName = "login-${loginJsHash}.js"
    public static let loginCSSName = "login-${loginCssHash}.css"

    /// Absolute paths for the page shell's \`<script>\` and \`<link>\`.
    public static let jsPath = "/assets/\\(jsName)"
    public static let cssPath = "/assets/\\(cssName)"
    public static let loginJSPath = "/assets/\\(loginJSName)"
    public static let loginCSSPath = "/assets/\\(loginCSSName)"

    /// Every asset the router will serve, keyed by the filename in its URL.
    /// A request for anything not in here is a 404 — there is no path
    /// traversal to get wrong because no filesystem is ever consulted.
    public static let assets: [String: (mime: String, body: String)] = [
        jsName: ("application/javascript; charset=utf-8", js),
        cssName: ("text/css; charset=utf-8", css),
        loginJSName: ("application/javascript; charset=utf-8", loginJS),
        loginCSSName: ("text/css; charset=utf-8", loginCSS),
    ]

    public static let js = ${rawLiteral(js)}

    public static let css = ${rawLiteral(css)}

    public static let loginJS = ${rawLiteral(loginJs)}

    public static let loginCSS = ${rawLiteral(loginCss)}
}
`

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, swift, 'utf8')

const kb = (s) => `${(Buffer.byteLength(s, 'utf8') / 1024).toFixed(1)} kB`
console.log('PortalBundle.swift written')
for (const [name, body] of [
  [`portal-${jsHash}.js`, js],
  [`portal-${cssHash}.css`, css],
  [`login-${loginJsHash}.js`, loginJs],
  [`login-${loginCssHash}.css`, loginCss],
]) {
  console.log(`  ${name.padEnd(34)} ${kb(body)}`)
}
