#!/usr/bin/env node

import { createHash } from 'node:crypto'
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const portalDir = join(here, '..')
const repoRoot = join(portalDir, '..')

const DIST = join(portalDir, 'dist')
const OUT = join(repoRoot, 'Sources', 'GoelCore', 'Remote', 'Generated', 'PortalBundle.swift')

/** The `\` scan deliberately omits `(`: an unguarded `\#n` in minified JS would corrupt the bundle. */
function rawLiteral(content) {
  let n = 1
  while (content.includes(`"""${'#'.repeat(n)}`) || content.includes(`\\${'#'.repeat(n)}`)) {
    n++
    if (n > 16) throw new Error('could not find a safe raw-string delimiter')
  }
  const h = '#'.repeat(n)
  // Closing delimiter must stay at column 0: Swift strips its indentation from every payload line.
  return `${h}"""\n${content}\n"""${h}`
}

function hash(content) {
  return createHash('sha256').update(content).digest('hex').slice(0, 16)
}

function read(path, hint) {
  try {
    return readFileSync(path, 'utf8')
  } catch {
    console.error(`error: ${path} is missing${hint ? ` — ${hint}` : ''}.`)
    process.exit(1)
  }
}

const built = (name) => read(join(DIST, name), 'run `npm run build` first')
const source = (...parts) => read(join(portalDir, 'src', ...parts))

const js = built('portal.js')
const css = built('portal.css')

// The Studio faces Vite emitted (content-hashed names, referenced relatively from the CSS). They
// are served from /assets/ like the bundle — `font-src 'self'` allows nothing else.
const fonts = readdirSync(DIST)
  .filter((name) => /^font-[\w.-]+\.woff2$/.test(name))
  .sort()
  .map((name) => [name, readFileSync(join(DIST, name)).toString('base64').match(/.{1,76}/g).join('\n')])
if (fonts.length === 0) {
  console.error('error: no font-*.woff2 in dist — did styles/fonts.css stop being imported?')
  process.exit(1)
}

// The sign-in page uses the same faces: copy the built @font-face rules, whose relative URLs
// resolve against /assets/ there too.
const fontFaces = (css.match(/@font-face\{[^}]*\}/g) ?? []).join('\n')

// Login CSS/JS ship as assets, never inline blocks, so the CSP can forbid inline script and style.
const loginCss = fontFaces + '\n' + source('styles', 'themes.css') + '\n' + source('login', 'login.css')
const loginJs = source('login', 'login.js')

// The installable-app bits: a service worker (text) and home-screen icons (binary, base64 in
// the Swift source, wrapped at 76 columns so no single line is huge).
const pwaDir = join(portalDir, 'pwa')
const serviceWorker = read(join(pwaDir, 'sw.js'))
const icon = (name) => {
  const b64 = readFileSync(join(pwaDir, name)).toString('base64')
  return b64.match(/.{1,76}/g).join('\n')
}
const icons = ['icon-192.png', 'icon-512.png', 'apple-touch-icon.png'].map((name) => [name, icon(name)])

const jsHash = hash(js)
const cssHash = hash(css)
const loginCssHash = hash(loginCss)
const loginJsHash = hash(loginJs)

const swift = `// Generated by \`cd portal && npm run build\` — DO NOT EDIT; hand edits are erased and fail CI.

import Foundation

public enum PortalBundle {

    /// Content-addressed: changing the bundle changes the URL, so a stale cache can't be served.
    public static let jsName = "portal-${jsHash}.js"
    public static let cssName = "portal-${cssHash}.css"
    public static let loginJSName = "login-${loginJsHash}.js"
    public static let loginCSSName = "login-${loginCssHash}.css"

    public static let jsPath = "/assets/\\(jsName)"
    public static let cssPath = "/assets/\\(cssName)"
    public static let loginJSPath = "/assets/\\(loginJSName)"
    public static let loginCSSPath = "/assets/\\(loginCSSName)"

    /// Keyed by filename; anything else 404s. No path traversal to get wrong — no filesystem is consulted.
    public static let assets: [String: (mime: String, body: String)] = [
        jsName: ("application/javascript; charset=utf-8", js),
        cssName: ("text/css; charset=utf-8", css),
        loginJSName: ("application/javascript; charset=utf-8", loginJS),
        loginCSSName: ("text/css; charset=utf-8", loginCSS),
    ]

    public static let js = ${rawLiteral(js)}

    public static let css = ${rawLiteral(css)}

    public static let loginJS = ${rawLiteral(loginJs)}

    public static let loginCSS = ${rawLiteral(loginCss)}

    public static let serviceWorker = ${rawLiteral(serviceWorker)}

    /// WOFF2 bodies of the Studio faces, base64 with line breaks; served from /assets/ by name.
    public static let fonts: [String: String] = [
${fonts.map(([name, b64]) => `        "${name}": ${rawLiteral(b64)},`).join('\n')}
    ]

    /// PNG bodies, base64 with line breaks; decode with \`.ignoreUnknownCharacters\`.
    public static let icons: [String: String] = [
${icons.map(([name, b64]) => `        "${name}": ${rawLiteral(b64)},`).join('\n')}
    ]
}
`

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, swift, 'utf8')

const kb = (s) => `${(Buffer.byteLength(s, 'utf8') / 1024).toFixed(1)} kB`
const fontBytes = (b64) => Buffer.from(b64.replace(/\n/g, ''), 'base64').length
console.log('PortalBundle.swift written')
for (const [name, body] of [
  [`portal-${jsHash}.js`, js],
  [`portal-${cssHash}.css`, css],
  [`login-${loginJsHash}.js`, loginJs],
  [`login-${loginCssHash}.css`, loginCss],
]) {
  console.log(`  ${name.padEnd(34)} ${kb(body)}`)
}
for (const [name, b64] of fonts) {
  console.log(`  ${name.padEnd(34)} ${(fontBytes(b64) / 1024).toFixed(1)} kB`)
}
