#!/usr/bin/env node

import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const portalDir = join(here, '..')
const repoRoot = join(portalDir, '..')

const DIST = join(portalDir, 'dist')
const OUT = join(repoRoot, 'Sources', 'GoelCore', 'Remote', 'Generated', 'PortalBundle.swift')

/** The `\` scan deliberately omits `(`: an unguarded `\#n` in minified JS would corrupt the bundle. */
function rawLiteral(content) {
  let n = 1
  while (content.includes(`"""${'#'.repeat(n)}`) || content.includes(`\\${'#'.repeat(n)}`)) {
    n++
    if (n > 16) throw new Error('could not find a safe raw-string delimiter')
  }
  const h = '#'.repeat(n)
  // Closing delimiter must stay at column 0: Swift strips its indentation from every payload line.
  return `${h}"""\n${content}\n"""${h}`
}

function hash(content) {
  return createHash('sha256').update(content).digest('hex').slice(0, 16)
}

function read(path, hint) {
  try {
    return readFileSync(path, 'utf8')
  } catch {
    console.error(`error: ${path} is missing${hint ? ` — ${hint}` : ''}.`)
    process.exit(1)
  }
}

const built = (name) => read(join(DIST, name), 'run `npm run build` first')
const source = (...parts) => read(join(portalDir, 'src', ...parts))

const js = built('portal.js')
const css = built('portal.css')

// Login CSS/JS ship as assets, never inline blocks, so the CSP can forbid inline script and style.
const loginCss = source('styles', 'themes.css') + '\n' + source('login', 'login.css')
const loginJs = source('login', 'login.js')

const jsHash = hash(js)
const cssHash = hash(css)
const loginCssHash = hash(loginCss)
const loginJsHash = hash(loginJs)

const swift = `// Generated by \`cd portal && npm run build\` — DO NOT EDIT; hand edits are erased and fail CI.

import Foundation

public enum PortalBundle {

    /// Content-addressed: changing the bundle changes the URL, so a stale cache can't be served.
    public static let jsName = "portal-${jsHash}.js"
    public static let cssName = "portal-${cssHash}.css"
    public static let loginJSName = "login-${loginJsHash}.js"
    public static let loginCSSName = "login-${loginCssHash}.css"

    public static let jsPath = "/assets/\\(jsName)"
    public static let cssPath = "/assets/\\(cssName)"
    public static let loginJSPath = "/assets/\\(loginJSName)"
    public static let loginCSSPath = "/assets/\\(loginCSSName)"

    /// Keyed by filename; anything else 404s. No path traversal to get wrong — no filesystem is consulted.
    public static let assets: [String: (mime: String, body: String)] = [
        jsName: ("application/javascript; charset=utf-8", js),
        cssName: ("text/css; charset=utf-8", css),
        loginJSName: ("application/javascript; charset=utf-8", loginJS),
        loginCSSName: ("text/css; charset=utf-8", loginCSS),
    ]

    public static let js = ${rawLiteral(js)}

    public static let css = ${rawLiteral(css)}

    public static let loginJS = ${rawLiteral(loginJs)}

    public static let loginCSS = ${rawLiteral(loginCss)}
}
`

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, swift, 'utf8')

const kb = (s) => `${(Buffer.byteLength(s, 'utf8') / 1024).toFixed(1)} kB`
console.log('PortalBundle.swift written')
for (const [name, body] of [
  [`portal-${jsHash}.js`, js],
  [`portal-${cssHash}.css`, css],
  [`login-${loginJsHash}.js`, loginJs],
  [`login-${loginCssHash}.css`, loginCss],
]) {
  console.log(`  ${name.padEnd(34)} ${kb(body)}`)
}
