import Foundation

public struct AppSettings: Codable, Sendable, Hashable {

    public var profiles: [TrafficProfile]

    public var selectedProfileName: String

    public var speedLimitEnabled: Bool

    public var defaultSaveDirectory: String

    public var theme: String

    public var language: String

    public var launchAtLogin: Bool

    public var launchMinimized: Bool

    public var menuBarExtraEnabled: Bool

    public var defaultFolderRule: String

    public var existingFileReaction: String

    public var clipboardMonitorEnabled: Bool

    public var hlsMaxHeight: Int

    public var detailPanelPosition: String

    public var proxyMode: String

    public var proxyType: String

    /// Reserved: not wired to the FTP/SFTP/BitTorrent engines yet — persisted but inert.
    public var proxyAllProtocols: Bool

    public var proxyHost: String

    public var proxyPort: Int

    public var connectionTimeout: Double

    public var retryCount: Int

    public var retryInterval: Double

    public var autoRetryEnabled: Bool

    public var autoRetryMaxAttempts: Int

    public var userAgent: String

    public var cookieAuthEnabled: Bool

    public var aggregationEnabled: Bool

    public var aggregationAdapterIds: [String]

    public var aggregationIncludeExpensive: Bool

    /// Allow binding outside an active VPN default route — a traffic leak; default off.
    public var aggregationAllowOutsideVPN: Bool

    public var aggregationStreamsPerAdapter: Int

    public var aggregationStrategy: String

    public var aggregationPathDiversityProbe: Bool

    public var btMakeDefaultClient: Bool

    public var btAutoDeleteTorrent: Bool

    public var btWatchFolderEnabled: Bool

    public var btWatchFolderPath: String

    public var btWatchStartWithoutConfirmation: Bool

    public var btEncryptionMode: String

    public var btEnableDHT: Bool

    public var btEnablePeX: Bool

    public var btEnableLPD: Bool

    public var btEnableUTP: Bool

    public var notifyOnAdded: Bool

    public var notifyOnCompleted: Bool

    public var notifyOnFailed: Bool

    public var notifyOnlyWhenInactive: Bool

    public var notificationSound: Bool

    public var preventSleepWhileDownloading: Bool

    public var allowSleepIfResumable: Bool

    public var allowSleepWhileSeeding: Bool

    public var pauseBelowBatteryThreshold: Bool

    public var batteryThresholdPercent: Int

    public var dontSeedOnBattery: Bool

    public var backupEnabled: Bool

    public var backupIntervalHours: Int

    public var antivirusEnabled: Bool

    public var antivirusScanner: String

    public var antivirusExecutablePath: String

    public var antivirusArgumentTemplate: String

    /// One-shot: must be reset to `none` after firing, or a forgotten toggle shuts the Mac down days later.
    public var autoShutdownAction: String

    public var scheduleEnabled: Bool

    public var scheduleStartMinute: Int

    public var scheduleEndMinute: Int

    public var scheduleDays: [Int]

    public var scheduleProfileName: String

    public var pauseOnExpensiveNetwork: Bool

    public var pauseOnConstrainedNetwork: Bool

    public var postDownloadExtractArchives: Bool

    public var postDownloadScriptEnabled: Bool

    public var postDownloadScriptPath: String

    public var postDownloadScriptArgs: String

    /// Opt-in by design: on, a finished file is silently replaced when the remote changes.
    public var autoRedownloadOnRemoteChange: Bool

    public var subtitleDownloadEnabled: Bool

    public var subtitleLanguages: String

    public var subtitleIncludeAutoGenerated: Bool

    /// `PATH` is never consulted (see `FFmpegService`): empty falls back to the bundled copy, then fixed system locations.
    public var ffmpegPath: String

    public var mediaConcurrency: Int

    public var remoteAccessEnabled: Bool

    public var remotePort: Int

    public var remoteToken: String

    public var remoteAllowLAN: Bool

    /// Off means anyone who reaches the port has full control — only sane on loopback.
    public var remoteRequireAuth: Bool

    public var remoteUsername: String

    /// A versioned salted-iterated hash (`"v1$saltHex$hashHex"`), never plaintext; write it via ``RemotePassword/hash(_:)``.
    public var remotePasswordHash: String

    public var remoteReadOnly: Bool

    public var remoteSessionMinutes: Int

    public var remoteTheme: String

    public var rssFeeds: [RSSFeed]

    public var rssPollIntervalMinutes: Int

    public var backupKeepCount: Int

    public var autoCheckUpdates: Bool

    public var updateFeedURL: String

    // Everything below must default to the portal's existing behaviour, so an existing install is unaffected until opted in.

    /// If the PKCS#12 identity won't load, the server refuses to fall back to cleartext.
    public var remoteTLSEnabled: Bool

    /// The passphrase comes from `GOEL_PORTAL_TLS_PASSPHRASE`, never from here — no secret in settings, backups or exports.
    public var remoteTLSIdentityPath: String

    /// Counted per client address, so one attacker cannot lock everyone else out of the portal.
    public var remoteLoginMaxAttempts: Int

    /// Doubles per failure to a 15-minute ceiling: that is what takes an online guess from thousands/sec to a handful/hour.
    public var remoteLoginBackoffSeconds: Double

    /// An auth bypass unless ``remoteTrustedProxies`` is set — off by default.
    public var remoteTrustedHeaderAuthEnabled: Bool

    public var remoteTrustedHeaderName: String

    /// Empty means "trust nobody", which disables header SSO; entries are literal IPs or IPv4 CIDR blocks.
    public var remoteTrustedProxies: [String]

    /// Local only — never uploaded or exported, and ``AuditLog`` redacts to host.
    public var auditLogEnabled: Bool

    public var auditLogDirectory: String

    public var auditLogRetentionDays: Int

    public var auditLogKeepFiles: Int

    public var auditLogMaxFileMegabytes: Int

    public init(
        profiles: [TrafficProfile] = TrafficProfile.defaults,
        selectedProfileName: String = TrafficProfile.medium.name,
        speedLimitEnabled: Bool = true,
        defaultSaveDirectory: String = AppSettings.systemDownloadsDirectory,
        theme: String = "frost-dark",
        language: String = "English",
        launchAtLogin: Bool = false,
        launchMinimized: Bool = false,
        menuBarExtraEnabled: Bool = true,
        defaultFolderRule: String = "fixed",
        existingFileReaction: String = "rename",
        clipboardMonitorEnabled: Bool = false,
        hlsMaxHeight: Int = 0,
        detailPanelPosition: String = "right",
        proxyMode: String = "none",
        proxyType: String = "http",
        proxyAllProtocols: Bool = false,
        proxyHost: String = "",
        proxyPort: Int = 0,
        connectionTimeout: Double = 30,
        retryCount: Int = 3,
        retryInterval: Double = 5,
        autoRetryEnabled: Bool = false,
        autoRetryMaxAttempts: Int = 5,
        userAgent: String = "GoelDownloader/1.0 (macOS)",
        cookieAuthEnabled: Bool = true,
        aggregationEnabled: Bool = false,
        aggregationAdapterIds: [String] = [],
        aggregationIncludeExpensive: Bool = false,
        aggregationAllowOutsideVPN: Bool = false,
        aggregationStreamsPerAdapter: Int = 2,
        aggregationStrategy: String = "roundRobin",
        aggregationPathDiversityProbe: Bool = false,
        btMakeDefaultClient: Bool = false,
        btAutoDeleteTorrent: Bool = false,
        btWatchFolderEnabled: Bool = false,
        btWatchFolderPath: String = "",
        btWatchStartWithoutConfirmation: Bool = false,
        btEncryptionMode: String = "prefer",
        btEnableDHT: Bool = true,
        btEnablePeX: Bool = true,
        btEnableLPD: Bool = true,
        btEnableUTP: Bool = true,
        notifyOnAdded: Bool = false,
        notifyOnCompleted: Bool = true,
        notifyOnFailed: Bool = true,
        notifyOnlyWhenInactive: Bool = false,
        notificationSound: Bool = true,
        preventSleepWhileDownloading: Bool = true,
        allowSleepIfResumable: Bool = false,
        allowSleepWhileSeeding: Bool = false,
        pauseBelowBatteryThreshold: Bool = false,
        batteryThresholdPercent: Int = 20,
        dontSeedOnBattery: Bool = false,
        backupEnabled: Bool = false,
        backupIntervalHours: Int = 24,
        antivirusEnabled: Bool = false,
        antivirusScanner: String = "",
        antivirusExecutablePath: String = "",
        antivirusArgumentTemplate: String = "%path%",
        autoShutdownAction: String = "none",
        scheduleEnabled: Bool = false,
        scheduleStartMinute: Int = 22 * 60,
        scheduleEndMinute: Int = 7 * 60,
        scheduleDays: [Int] = [1, 2, 3, 4, 5, 6, 7],
        scheduleProfileName: String = "",
        pauseOnExpensiveNetwork: Bool = false,
        pauseOnConstrainedNetwork: Bool = false,
        postDownloadExtractArchives: Bool = false,
        postDownloadScriptEnabled: Bool = false,
        postDownloadScriptPath: String = "",
        postDownloadScriptArgs: String = "%path%",
        autoRedownloadOnRemoteChange: Bool = false,
        subtitleDownloadEnabled: Bool = false,
        subtitleLanguages: String = "en",
        subtitleIncludeAutoGenerated: Bool = false,
        ffmpegPath: String = "",
        mediaConcurrency: Int = 2,
        remoteAccessEnabled: Bool = false,
        remotePort: Int = 8899,
        remoteToken: String = "",
        remoteAllowLAN: Bool = false,
        remoteRequireAuth: Bool = true,
        remoteUsername: String = "admin",
        remotePasswordHash: String = "",
        remoteReadOnly: Bool = false,
        remoteSessionMinutes: Int = 120,
        remoteTheme: String = "frost-dark",
        rssFeeds: [RSSFeed] = [],
        rssPollIntervalMinutes: Int = 30,
        backupKeepCount: Int = 20,
        autoCheckUpdates: Bool = false,
        updateFeedURL: String = "",
        remoteTLSEnabled: Bool = false,
        remoteTLSIdentityPath: String = "",
        remoteLoginMaxAttempts: Int = 5,
        remoteLoginBackoffSeconds: Double = 5,
        remoteTrustedHeaderAuthEnabled: Bool = false,
        remoteTrustedHeaderName: String = "X-Forwarded-User",
        remoteTrustedProxies: [String] = [],
        auditLogEnabled: Bool = false,
        auditLogDirectory: String = "",
        auditLogRetentionDays: Int = 90,
        auditLogKeepFiles: Int = 12,
        auditLogMaxFileMegabytes: Int = 8
    ) {
        self.profiles = profiles
        self.selectedProfileName = selectedProfileName
        self.speedLimitEnabled = speedLimitEnabled
        self.defaultSaveDirectory = defaultSaveDirectory
        self.theme = theme
        self.language = language
        self.launchAtLogin = launchAtLogin
        self.launchMinimized = launchMinimized
        self.menuBarExtraEnabled = menuBarExtraEnabled
        self.defaultFolderRule = defaultFolderRule
        self.existingFileReaction = existingFileReaction
        self.clipboardMonitorEnabled = clipboardMonitorEnabled
        self.hlsMaxHeight = hlsMaxHeight
        self.detailPanelPosition = detailPanelPosition
        self.proxyMode = proxyMode
        self.proxyType = proxyType
        self.proxyAllProtocols = proxyAllProtocols
        self.proxyHost = proxyHost
        self.proxyPort = proxyPort
        self.connectionTimeout = connectionTimeout
        self.retryCount = retryCount
        self.retryInterval = retryInterval
        self.autoRetryEnabled = autoRetryEnabled
        self.autoRetryMaxAttempts = autoRetryMaxAttempts
        self.userAgent = userAgent
        self.cookieAuthEnabled = cookieAuthEnabled
        self.aggregationEnabled = aggregationEnabled
        self.aggregationAdapterIds = aggregationAdapterIds
        self.aggregationIncludeExpensive = aggregationIncludeExpensive
        self.aggregationAllowOutsideVPN = aggregationAllowOutsideVPN
        self.aggregationStreamsPerAdapter = aggregationStreamsPerAdapter
        self.aggregationStrategy = aggregationStrategy
        self.aggregationPathDiversityProbe = aggregationPathDiversityProbe
        self.btMakeDefaultClient = btMakeDefaultClient
        self.btAutoDeleteTorrent = btAutoDeleteTorrent
        self.btWatchFolderEnabled = btWatchFolderEnabled
        self.btWatchFolderPath = btWatchFolderPath
        self.btWatchStartWithoutConfirmation = btWatchStartWithoutConfirmation
        self.btEncryptionMode = btEncryptionMode
        self.btEnableDHT = btEnableDHT
        self.btEnablePeX = btEnablePeX
        self.btEnableLPD = btEnableLPD
        self.btEnableUTP = btEnableUTP
        self.notifyOnAdded = notifyOnAdded
        self.notifyOnCompleted = notifyOnCompleted
        self.notifyOnFailed = notifyOnFailed
        self.notifyOnlyWhenInactive = notifyOnlyWhenInactive
        self.notificationSound = notificationSound
        self.preventSleepWhileDownloading = preventSleepWhileDownloading
        self.allowSleepIfResumable = allowSleepIfResumable
        self.allowSleepWhileSeeding = allowSleepWhileSeeding
        self.pauseBelowBatteryThreshold = pauseBelowBatteryThreshold
        self.batteryThresholdPercent = batteryThresholdPercent
        self.dontSeedOnBattery = dontSeedOnBattery
        self.backupEnabled = backupEnabled
        self.backupIntervalHours = backupIntervalHours
        self.antivirusEnabled = antivirusEnabled
        self.antivirusScanner = antivirusScanner
        self.antivirusExecutablePath = antivirusExecutablePath
        self.antivirusArgumentTemplate = antivirusArgumentTemplate
        self.autoShutdownAction = autoShutdownAction
        self.scheduleEnabled = scheduleEnabled
        self.scheduleStartMinute = scheduleStartMinute
        self.scheduleEndMinute = scheduleEndMinute
        self.scheduleDays = scheduleDays
        self.scheduleProfileName = scheduleProfileName
        self.pauseOnExpensiveNetwork = pauseOnExpensiveNetwork
        self.pauseOnConstrainedNetwork = pauseOnConstrainedNetwork
        self.postDownloadExtractArchives = postDownloadExtractArchives
        self.postDownloadScriptEnabled = postDownloadScriptEnabled
        self.postDownloadScriptPath = postDownloadScriptPath
        self.postDownloadScriptArgs = postDownloadScriptArgs
        self.autoRedownloadOnRemoteChange = autoRedownloadOnRemoteChange
        self.subtitleDownloadEnabled = subtitleDownloadEnabled
        self.subtitleLanguages = subtitleLanguages
        self.subtitleIncludeAutoGenerated = subtitleIncludeAutoGenerated
        self.ffmpegPath = ffmpegPath
        self.mediaConcurrency = mediaConcurrency
        self.remoteAccessEnabled = remoteAccessEnabled
        self.remotePort = remotePort
        self.remoteToken = remoteToken
        self.remoteAllowLAN = remoteAllowLAN
        self.remoteRequireAuth = remoteRequireAuth
        self.remoteUsername = remoteUsername
        self.remotePasswordHash = remotePasswordHash
        self.remoteReadOnly = remoteReadOnly
        self.remoteSessionMinutes = remoteSessionMinutes
        self.remoteTheme = remoteTheme
        self.rssFeeds = rssFeeds
        self.rssPollIntervalMinutes = rssPollIntervalMinutes
        self.backupKeepCount = backupKeepCount
        self.autoCheckUpdates = autoCheckUpdates
        self.updateFeedURL = updateFeedURL
        self.remoteTLSEnabled = remoteTLSEnabled
        self.remoteTLSIdentityPath = remoteTLSIdentityPath
        self.remoteLoginMaxAttempts = remoteLoginMaxAttempts
        self.remoteLoginBackoffSeconds = remoteLoginBackoffSeconds
        self.remoteTrustedHeaderAuthEnabled = remoteTrustedHeaderAuthEnabled
        self.remoteTrustedHeaderName = remoteTrustedHeaderName
        self.remoteTrustedProxies = remoteTrustedProxies
        self.auditLogEnabled = auditLogEnabled
        self.auditLogDirectory = auditLogDirectory
        self.auditLogRetentionDays = auditLogRetentionDays
        self.auditLogKeepFiles = auditLogKeepFiles
        self.auditLogMaxFileMegabytes = auditLogMaxFileMegabytes
    }

    private enum CodingKeys: String, CodingKey {
        case profiles, selectedProfileName, speedLimitEnabled, defaultSaveDirectory
        case theme, language, launchAtLogin, launchMinimized, menuBarExtraEnabled, defaultFolderRule
        case existingFileReaction, clipboardMonitorEnabled, hlsMaxHeight, detailPanelPosition
        case proxyMode, proxyType, proxyAllProtocols, proxyHost, proxyPort, connectionTimeout, retryCount
        case retryInterval, autoRetryEnabled, autoRetryMaxAttempts, userAgent, cookieAuthEnabled
        case aggregationEnabled, aggregationAdapterIds, aggregationIncludeExpensive
        case aggregationAllowOutsideVPN, aggregationStreamsPerAdapter, aggregationStrategy
        case aggregationPathDiversityProbe
        case btMakeDefaultClient, btAutoDeleteTorrent, btWatchFolderEnabled
        case btWatchFolderPath, btWatchStartWithoutConfirmation, btEncryptionMode
        case btEnableDHT, btEnablePeX, btEnableLPD, btEnableUTP
        case notifyOnAdded, notifyOnCompleted, notifyOnFailed
        case notifyOnlyWhenInactive, notificationSound
        case preventSleepWhileDownloading, allowSleepIfResumable, allowSleepWhileSeeding
        case pauseBelowBatteryThreshold, batteryThresholdPercent, dontSeedOnBattery
        case backupEnabled, backupIntervalHours
        case antivirusEnabled, antivirusScanner, antivirusExecutablePath, antivirusArgumentTemplate
        case autoShutdownAction
        case scheduleEnabled, scheduleStartMinute, scheduleEndMinute, scheduleDays, scheduleProfileName
        case pauseOnExpensiveNetwork, pauseOnConstrainedNetwork
        case postDownloadExtractArchives, postDownloadScriptEnabled
        case postDownloadScriptPath, postDownloadScriptArgs
        case autoRedownloadOnRemoteChange
        case subtitleDownloadEnabled, subtitleLanguages, subtitleIncludeAutoGenerated, ffmpegPath
        case mediaConcurrency
        case remoteAccessEnabled, remotePort, remoteToken, remoteAllowLAN
        case remoteRequireAuth, remoteUsername, remotePasswordHash, remoteReadOnly
        case remoteSessionMinutes, remoteTheme
        case rssFeeds, rssPollIntervalMinutes
        case backupKeepCount
        case autoCheckUpdates, updateFeedURL
        case remoteTLSEnabled, remoteTLSIdentityPath
        case remoteLoginMaxAttempts, remoteLoginBackoffSeconds
        case remoteTrustedHeaderAuthEnabled, remoteTrustedHeaderName, remoteTrustedProxies
        case auditLogEnabled, auditLogDirectory
        case auditLogRetentionDays, auditLogKeepFiles, auditLogMaxFileMegabytes
    }

    /// Every field must use `decodeIfPresent` with a default, or blobs written before a key existed throw on load.
    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        profiles = try c.decodeIfPresent([TrafficProfile].self, forKey: .profiles) ?? TrafficProfile.defaults
        selectedProfileName = try c.decodeIfPresent(String.self, forKey: .selectedProfileName) ?? TrafficProfile.medium.name
        speedLimitEnabled = try c.decodeIfPresent(Bool.self, forKey: .speedLimitEnabled) ?? true
        defaultSaveDirectory = try c.decodeIfPresent(String.self, forKey: .defaultSaveDirectory) ?? AppSettings.systemDownloadsDirectory
        theme = try c.decodeIfPresent(String.self, forKey: .theme) ?? "system"
        language = try c.decodeIfPresent(String.self, forKey: .language) ?? "English"
        launchAtLogin = try c.decodeIfPresent(Bool.self, forKey: .launchAtLogin) ?? false
        launchMinimized = try c.decodeIfPresent(Bool.self, forKey: .launchMinimized) ?? false
        menuBarExtraEnabled = try c.decodeIfPresent(Bool.self, forKey: .menuBarExtraEnabled) ?? true
        defaultFolderRule = try c.decodeIfPresent(String.self, forKey: .defaultFolderRule) ?? "fixed"
        existingFileReaction = try c.decodeIfPresent(String.self, forKey: .existingFileReaction) ?? "rename"
        clipboardMonitorEnabled = try c.decodeIfPresent(Bool.self, forKey: .clipboardMonitorEnabled) ?? false
        hlsMaxHeight = try c.decodeIfPresent(Int.self, forKey: .hlsMaxHeight) ?? 0
        detailPanelPosition = try c.decodeIfPresent(String.self, forKey: .detailPanelPosition) ?? "right"
        proxyMode = try c.decodeIfPresent(String.self, forKey: .proxyMode) ?? "none"
        proxyType = try c.decodeIfPresent(String.self, forKey: .proxyType) ?? "http"
        proxyAllProtocols = try c.decodeIfPresent(Bool.self, forKey: .proxyAllProtocols) ?? false
        proxyHost = try c.decodeIfPresent(String.self, forKey: .proxyHost) ?? ""
        proxyPort = try c.decodeIfPresent(Int.self, forKey: .proxyPort) ?? 0
        connectionTimeout = try c.decodeIfPresent(Double.self, forKey: .connectionTimeout) ?? 30
        retryCount = try c.decodeIfPresent(Int.self, forKey: .retryCount) ?? 3
        retryInterval = try c.decodeIfPresent(Double.self, forKey: .retryInterval) ?? 5
        autoRetryEnabled = try c.decodeIfPresent(Bool.self, forKey: .autoRetryEnabled) ?? false
        autoRetryMaxAttempts = try c.decodeIfPresent(Int.self, forKey: .autoRetryMaxAttempts) ?? 5
        userAgent = try c.decodeIfPresent(String.self, forKey: .userAgent) ?? "GoelDownloader/1.0 (macOS)"
        cookieAuthEnabled = try c.decodeIfPresent(Bool.self, forKey: .cookieAuthEnabled) ?? true
        aggregationEnabled = try c.decodeIfPresent(Bool.self, forKey: .aggregationEnabled) ?? false
        aggregationAdapterIds = try c.decodeIfPresent([String].self, forKey: .aggregationAdapterIds) ?? []
        aggregationIncludeExpensive = try c.decodeIfPresent(Bool.self, forKey: .aggregationIncludeExpensive) ?? false
        aggregationAllowOutsideVPN = try c.decodeIfPresent(Bool.self, forKey: .aggregationAllowOutsideVPN) ?? false
        aggregationStreamsPerAdapter = try c.decodeIfPresent(Int.self, forKey: .aggregationStreamsPerAdapter) ?? 2
        aggregationStrategy = try c.decodeIfPresent(String.self, forKey: .aggregationStrategy) ?? "roundRobin"
        aggregationPathDiversityProbe = try c.decodeIfPresent(Bool.self, forKey: .aggregationPathDiversityProbe) ?? false
        btMakeDefaultClient = try c.decodeIfPresent(Bool.self, forKey: .btMakeDefaultClient) ?? false
        btAutoDeleteTorrent = try c.decodeIfPresent(Bool.self, forKey: .btAutoDeleteTorrent) ?? false
        btWatchFolderEnabled = try c.decodeIfPresent(Bool.self, forKey: .btWatchFolderEnabled) ?? false
        btWatchFolderPath = try c.decodeIfPresent(String.self, forKey: .btWatchFolderPath) ?? ""
        btWatchStartWithoutConfirmation = try c.decodeIfPresent(Bool.self, forKey: .btWatchStartWithoutConfirmation) ?? false
        btEncryptionMode = try c.decodeIfPresent(String.self, forKey: .btEncryptionMode) ?? "prefer"
        btEnableDHT = try c.decodeIfPresent(Bool.self, forKey: .btEnableDHT) ?? true
        btEnablePeX = try c.decodeIfPresent(Bool.self, forKey: .btEnablePeX) ?? true
        btEnableLPD = try c.decodeIfPresent(Bool.self, forKey: .btEnableLPD) ?? true
        btEnableUTP = try c.decodeIfPresent(Bool.self, forKey: .btEnableUTP) ?? true
        notifyOnAdded = try c.decodeIfPresent(Bool.self, forKey: .notifyOnAdded) ?? false
        notifyOnCompleted = try c.decodeIfPresent(Bool.self, forKey: .notifyOnCompleted) ?? true
        notifyOnFailed = try c.decodeIfPresent(Bool.self, forKey: .notifyOnFailed) ?? true
        notifyOnlyWhenInactive = try c.decodeIfPresent(Bool.self, forKey: .notifyOnlyWhenInactive) ?? false
        notificationSound = try c.decodeIfPresent(Bool.self, forKey: .notificationSound) ?? true
        preventSleepWhileDownloading = try c.decodeIfPresent(Bool.self, forKey: .preventSleepWhileDownloading) ?? true
        allowSleepIfResumable = try c.decodeIfPresent(Bool.self, forKey: .allowSleepIfResumable) ?? false
        allowSleepWhileSeeding = try c.decodeIfPresent(Bool.self, forKey: .allowSleepWhileSeeding) ?? false
        pauseBelowBatteryThreshold = try c.decodeIfPresent(Bool.self, forKey: .pauseBelowBatteryThreshold) ?? false
        batteryThresholdPercent = try c.decodeIfPresent(Int.self, forKey: .batteryThresholdPercent) ?? 20
        dontSeedOnBattery = try c.decodeIfPresent(Bool.self, forKey: .dontSeedOnBattery) ?? false
        backupEnabled = try c.decodeIfPresent(Bool.self, forKey: .backupEnabled) ?? false
        backupIntervalHours = try c.decodeIfPresent(Int.self, forKey: .backupIntervalHours) ?? 24
        antivirusEnabled = try c.decodeIfPresent(Bool.self, forKey: .antivirusEnabled) ?? false
        antivirusScanner = try c.decodeIfPresent(String.self, forKey: .antivirusScanner) ?? ""
        antivirusExecutablePath = try c.decodeIfPresent(String.self, forKey: .antivirusExecutablePath) ?? ""
        antivirusArgumentTemplate = try c.decodeIfPresent(String.self, forKey: .antivirusArgumentTemplate) ?? "%path%"
        autoShutdownAction = try c.decodeIfPresent(String.self, forKey: .autoShutdownAction) ?? "none"
        scheduleEnabled = try c.decodeIfPresent(Bool.self, forKey: .scheduleEnabled) ?? false
        scheduleStartMinute = try c.decodeIfPresent(Int.self, forKey: .scheduleStartMinute) ?? 22 * 60
        scheduleEndMinute = try c.decodeIfPresent(Int.self, forKey: .scheduleEndMinute) ?? 7 * 60
        scheduleDays = try c.decodeIfPresent([Int].self, forKey: .scheduleDays) ?? [1, 2, 3, 4, 5, 6, 7]
        scheduleProfileName = try c.decodeIfPresent(String.self, forKey: .scheduleProfileName) ?? ""
        pauseOnExpensiveNetwork = try c.decodeIfPresent(Bool.self, forKey: .pauseOnExpensiveNetwork) ?? false
        pauseOnConstrainedNetwork = try c.decodeIfPresent(Bool.self, forKey: .pauseOnConstrainedNetwork) ?? false
        postDownloadExtractArchives = try c.decodeIfPresent(Bool.self, forKey: .postDownloadExtractArchives) ?? false
        postDownloadScriptEnabled = try c.decodeIfPresent(Bool.self, forKey: .postDownloadScriptEnabled) ?? false
        postDownloadScriptPath = try c.decodeIfPresent(String.self, forKey: .postDownloadScriptPath) ?? ""
        postDownloadScriptArgs = try c.decodeIfPresent(String.self, forKey: .postDownloadScriptArgs) ?? "%path%"
        autoRedownloadOnRemoteChange = try c.decodeIfPresent(Bool.self, forKey: .autoRedownloadOnRemoteChange) ?? false
        subtitleDownloadEnabled = try c.decodeIfPresent(Bool.self, forKey: .subtitleDownloadEnabled) ?? false
        subtitleLanguages = try c.decodeIfPresent(String.self, forKey: .subtitleLanguages) ?? "en"
        subtitleIncludeAutoGenerated = try c.decodeIfPresent(Bool.self, forKey: .subtitleIncludeAutoGenerated) ?? false
        ffmpegPath = try c.decodeIfPresent(String.self, forKey: .ffmpegPath) ?? ""
        // Clamped on the way in: a hand-edited 0 or negative stalls the queue with jobs that can never start.
        mediaConcurrency = max(1, try c.decodeIfPresent(Int.self, forKey: .mediaConcurrency) ?? 2)
        remoteAccessEnabled = try c.decodeIfPresent(Bool.self, forKey: .remoteAccessEnabled) ?? false
        remotePort = try c.decodeIfPresent(Int.self, forKey: .remotePort) ?? 8899
        remoteToken = try c.decodeIfPresent(String.self, forKey: .remoteToken) ?? ""
        remoteAllowLAN = try c.decodeIfPresent(Bool.self, forKey: .remoteAllowLAN) ?? false
        remoteRequireAuth = try c.decodeIfPresent(Bool.self, forKey: .remoteRequireAuth) ?? true
        remoteUsername = try c.decodeIfPresent(String.self, forKey: .remoteUsername) ?? "admin"
        remotePasswordHash = try c.decodeIfPresent(String.self, forKey: .remotePasswordHash) ?? ""
        remoteReadOnly = try c.decodeIfPresent(Bool.self, forKey: .remoteReadOnly) ?? false
        remoteSessionMinutes = try c.decodeIfPresent(Int.self, forKey: .remoteSessionMinutes) ?? 120
        remoteTheme = try c.decodeIfPresent(String.self, forKey: .remoteTheme) ?? "frost-dark"
        rssFeeds = try c.decodeIfPresent([RSSFeed].self, forKey: .rssFeeds) ?? []
        rssPollIntervalMinutes = try c.decodeIfPresent(Int.self, forKey: .rssPollIntervalMinutes) ?? 30
        backupKeepCount = try c.decodeIfPresent(Int.self, forKey: .backupKeepCount) ?? 20
        autoCheckUpdates = try c.decodeIfPresent(Bool.self, forKey: .autoCheckUpdates) ?? false
        updateFeedURL = try c.decodeIfPresent(String.self, forKey: .updateFeedURL) ?? ""
        remoteTLSEnabled = try c.decodeIfPresent(Bool.self, forKey: .remoteTLSEnabled) ?? false
        remoteTLSIdentityPath = try c.decodeIfPresent(String.self, forKey: .remoteTLSIdentityPath) ?? ""
        remoteLoginMaxAttempts = try c.decodeIfPresent(Int.self, forKey: .remoteLoginMaxAttempts) ?? 5
        remoteLoginBackoffSeconds = try c.decodeIfPresent(Double.self, forKey: .remoteLoginBackoffSeconds) ?? 5
        remoteTrustedHeaderAuthEnabled = try c.decodeIfPresent(Bool.self, forKey: .remoteTrustedHeaderAuthEnabled) ?? false
        remoteTrustedHeaderName = try c.decodeIfPresent(String.self, forKey: .remoteTrustedHeaderName) ?? "X-Forwarded-User"
        remoteTrustedProxies = try c.decodeIfPresent([String].self, forKey: .remoteTrustedProxies) ?? []
        auditLogEnabled = try c.decodeIfPresent(Bool.self, forKey: .auditLogEnabled) ?? false
        auditLogDirectory = try c.decodeIfPresent(String.self, forKey: .auditLogDirectory) ?? ""
        auditLogRetentionDays = try c.decodeIfPresent(Int.self, forKey: .auditLogRetentionDays) ?? 90
        auditLogKeepFiles = try c.decodeIfPresent(Int.self, forKey: .auditLogKeepFiles) ?? 12
        auditLogMaxFileMegabytes = try c.decodeIfPresent(Int.self, forKey: .auditLogMaxFileMegabytes) ?? 8
    }

    public var selectedProfile: TrafficProfile {
        profiles.first { $0.name == selectedProfileName }
            ?? profiles.first
            ?? .medium
    }

    public var effectiveProfile: TrafficProfile {
        guard !speedLimitEnabled else { return selectedProfile }
        var profile = selectedProfile
        profile.maxDownloadBytesPerSec = 0
        profile.maxUploadBytesPerSec = 0
        return profile
    }

    public static var systemDownloadsDirectory: String {
        FileManager.default
            .urls(for: .downloadsDirectory, in: .userDomainMask)
            .first?
            .path
            ?? NSTemporaryDirectory()
    }
}
