#!/usr/bin/env python3
"""Regenerates `en.lproj/Localizable.strings` from every literal `L10n.t("…")` key in Sources/.

The key *is* the English text, so the base table maps each key to itself. It exists so a
missing-key audit has something to check against, and so translators have one file listing
every string the app can show. `L10n.t(someExpression)` call sites are skipped: those keys
live on the model type that produced the value, and the key-is-English fallback covers them.

Usage:  python3 Scripts/extract-l10n-keys.py [--check]
        python3 Scripts/extract-l10n-keys.py --coverage <code> [--min PERCENT]
        python3 Scripts/extract-l10n-keys.py --coverage-supported [--min PERCENT]
        --check exits non-zero if the committed table is out of date, for CI.
        --coverage prints how much of the base table <code>.lproj translates; with --min it
            exits non-zero below that percentage.
        --coverage-supported checks every language offered in L10n.supportedLanguages
            (Sources/GoelCore/Localization.swift) against --min, default 95, for CI: a
            language is only offered to users once it is (almost) fully translated.
"""

import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCES = os.path.join(ROOT, "Sources")
RESOURCES = os.path.join(ROOT, "Sources/GoelCore/Resources")
TABLE = os.path.join(RESOURCES, "en.lproj/Localizable.strings")
LOCALIZATION_SWIFT = os.path.join(ROOT, "Sources/GoelCore/Localization.swift")
DEFAULT_MIN_COVERAGE = 95.0

HEADER = """/* Goel° — base (English) strings. Generated by Scripts/extract-l10n-keys.py; do not
   hand-edit. The key is the English text, so this table maps each key to itself: it is the
   reference every translation mirrors, and the list a missing-key audit checks against.
   Keys arriving from model properties (`L10n.t(task.statusLabel)`) are absent by design —
   L10n.lookup falls back to the key, which already reads as English.

   To add a language: copy this file to <code>.lproj/Localizable.strings and translate the
   right-hand side of each line. Untranslated keys fall back to English automatically. */
"""


def swift_string_literals(text, index):
    """Reads one or more `+`-joined Swift string literals starting at `index`.

    Returns (value, next_index), or (None, index) when the expression is not a plain
    literal — an interpolated or computed key, which this script deliberately skips.
    """
    parts = []
    while True:
        while index < len(text) and text[index] in " \t\r\n":
            index += 1
        if text.startswith('"""', index):
            index += 3
            # Swift strips the newline right after the opening delimiter and the indentation
            # matching the closing one; reproducing that exactly is what makes the emitted key
            # byte-identical to the runtime one.
            end = text.find('"""', index)
            if end == -1:
                return None, index
            raw = text[index:end]
            index = end + 3
            lines = raw.split("\n")
            if lines and lines[0].strip() == "":
                lines = lines[1:]
            indent = ""
            if lines:
                closing = lines[-1]
                indent = closing[: len(closing) - len(closing.lstrip())]
                lines = lines[:-1]
            def dedent(ln):
                if ln.startswith(indent):
                    return ln[len(indent):]
                # A short line that is all whitespace collapses to empty in Swift; a short line
                # with content is a compile error, so it can never reach us.
                return "" if ln.strip() == "" else ln

            joined = "\n".join(dedent(ln) for ln in lines)
            # A trailing backslash in a multi-line literal continues the line, as in source.
            while "\\\n" in joined:
                joined = joined.replace("\\\n", "")
            parts.append(joined)
        elif index < len(text) and text[index] == '"':
            index += 1
            out = []
            while index < len(text):
                ch = text[index]
                if ch == "\\":
                    nxt = text[index + 1] if index + 1 < len(text) else ""
                    if nxt == "(":
                        return None, index  # interpolated — not a static key
                    out.append({"n": "\n", "t": "\t", '"': '"', "\\": "\\", "0": "\0"}.get(nxt, nxt))
                    index += 2
                    continue
                if ch == '"':
                    index += 1
                    break
                out.append(ch)
                index += 1
            parts.append("".join(out))
        else:
            return None, index

        save = index
        while index < len(text) and text[index] in " \t\r\n":
            index += 1
        if index < len(text) and text[index] == "+":
            index += 1
            continue
        return "".join(parts), save


def keys_in(path):
    text = io.open(path, encoding="utf-8").read()
    found = []
    needle = "L10n.t("
    i = text.find(needle)
    while i != -1:
        value, _ = swift_string_literals(text, i + len(needle))
        if value:
            found.append(value)
        i = text.find(needle, i + len(needle))
    return found


def escape(value):
    return (value.replace("\\", "\\\\")
                 .replace('"', '\\"')
                 .replace("\n", "\\n")
                 .replace("\t", "\\t"))


def render():
    keys = set()
    for base, _, files in os.walk(SOURCES):
        for name in sorted(files):
            if name.endswith(".swift"):
                keys.update(keys_in(os.path.join(base, name)))
    body = "".join('"%s" = "%s";\n' % (escape(k), escape(k)) for k in sorted(keys))
    return HEADER + "\n" + body, len(keys)


def parse_strings(path):
    """Parses an old-style `.strings` table into {key: value}, skipping comments.

    A small scanner rather than a regex, so a quote or `/*` inside a key cannot desync it.
    """
    text = io.open(path, encoding="utf-8").read()
    tokens = []
    i, n = 0, len(text)
    while i < n:
        ch = text[i]
        if text.startswith("/*", i):
            end = text.find("*/", i + 2)
            i = n if end == -1 else end + 2
        elif text.startswith("//", i):
            end = text.find("\n", i)
            i = n if end == -1 else end + 1
        elif ch == '"':
            i += 1
            out = []
            while i < n and text[i] != '"':
                if text[i] == "\\" and i + 1 < n:
                    nxt = text[i + 1]
                    out.append({"n": "\n", "t": "\t", '"': '"', "\\": "\\"}.get(nxt, nxt))
                    i += 2
                else:
                    out.append(text[i])
                    i += 1
            tokens.append(("str", "".join(out)))
            i += 1
        elif ch in "=;":
            tokens.append((ch, ch))
            i += 1
        else:
            i += 1
    table = {}
    for k in range(len(tokens) - 3):
        a, b, c, d = tokens[k:k + 4]
        if a[0] == "str" and b[0] == "=" and c[0] == "str" and d[0] == ";":
            table[a[1]] = c[1]
    return table


def coverage(code):
    """Percentage of base-table keys that <code>.lproj translates (non-empty value)."""
    base = parse_strings(TABLE)
    path = os.path.join(RESOURCES, "%s.lproj" % code, "Localizable.strings")
    if code == "en":
        return 100.0, len(base), len(base)
    if not os.path.exists(path):
        return 0.0, 0, len(base)
    table = parse_strings(path)
    translated = sum(1 for key in base if table.get(key))
    return (100.0 * translated / len(base) if base else 0.0), translated, len(base)


def supported_codes():
    """Language codes listed in `L10n.supportedLanguages`, read from the Swift source."""
    text = io.open(LOCALIZATION_SWIFT, encoding="utf-8").read()
    match = re.search(r"supportedLanguages[^=]*=\s*\[(.*?)\]", text, re.S)
    if not match:
        raise SystemExit("could not find L10n.supportedLanguages in %s" % LOCALIZATION_SWIFT)
    body = "\n".join(line.split("//", 1)[0] for line in match.group(1).splitlines())
    return re.findall(r'\(\s*"[^"]*"\s*,\s*"([^"]+)"\s*\)', body)


def option_value(flag):
    if flag not in sys.argv:
        return None
    index = sys.argv.index(flag)
    if index + 1 >= len(sys.argv):
        raise SystemExit("%s needs a value" % flag)
    return sys.argv[index + 1]


def report_coverage(codes, minimum):
    failed = False
    for code in codes:
        percent, translated, total = coverage(code)
        verdict = ""
        if minimum is not None and percent < minimum:
            verdict = "  BELOW %.0f%%" % minimum
            failed = True
        print("%s: %.1f%% (%d of %d strings translated)%s" % (code, percent, translated, total, verdict))
    return 1 if failed else 0


def main():
    minimum = option_value("--min")
    minimum = float(minimum) if minimum is not None else None
    if "--coverage-supported" in sys.argv:
        codes = supported_codes()
        if not codes:
            print("L10n.supportedLanguages lists no languages")
            return 1
        return report_coverage(codes, DEFAULT_MIN_COVERAGE if minimum is None else minimum)
    code = option_value("--coverage")
    if code is not None:
        return report_coverage([code], minimum)

    rendered, count = render()
    if "--check" in sys.argv:
        current = io.open(TABLE, encoding="utf-8").read()
        if current != rendered:
            print("en.lproj/Localizable.strings is out of date — run Scripts/extract-l10n-keys.py")
            return 1
        print("en.lproj/Localizable.strings is up to date (%d keys)" % count)
        return 0
    io.open(TABLE, "w", encoding="utf-8").write(rendered)
    print("wrote %d keys to %s" % (count, os.path.relpath(TABLE, ROOT)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
