#!/usr/bin/env python3
"""Regenerates `en.lproj/Localizable.strings` from every literal `L10n.t("…")` key in Sources/.

The key *is* the English text, so the base table maps each key to itself. It exists so a
missing-key audit has something to check against, and so translators have one file listing
every string the app can show. `L10n.t(someExpression)` call sites are skipped: those keys
live on the model type that produced the value, and the key-is-English fallback covers them.

Usage:  python3 Scripts/extract-l10n-keys.py [--check]
        --check exits non-zero if the committed table is out of date, for CI.
"""

import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCES = os.path.join(ROOT, "Sources")
TABLE = os.path.join(ROOT, "Sources/GoelCore/Resources/en.lproj/Localizable.strings")

HEADER = """/* Goel° — base (English) strings. Generated by Scripts/extract-l10n-keys.py; do not
   hand-edit. The key is the English text, so this table maps each key to itself: it is the
   reference every translation mirrors, and the list a missing-key audit checks against.
   Keys arriving from model properties (`L10n.t(task.statusLabel)`) are absent by design —
   L10n.lookup falls back to the key, which already reads as English.

   To add a language: copy this file to <code>.lproj/Localizable.strings and translate the
   right-hand side of each line. Untranslated keys fall back to English automatically. */
"""


def swift_string_literals(text, index):
    """Reads one or more `+`-joined Swift string literals starting at `index`.

    Returns (value, next_index), or (None, index) when the expression is not a plain
    literal — an interpolated or computed key, which this script deliberately skips.
    """
    parts = []
    while True:
        while index < len(text) and text[index] in " \t\r\n":
            index += 1
        if text.startswith('"""', index):
            index += 3
            # Swift strips the newline right after the opening delimiter and the indentation
            # matching the closing one; reproducing that exactly is what makes the emitted key
            # byte-identical to the runtime one.
            end = text.find('"""', index)
            if end == -1:
                return None, index
            raw = text[index:end]
            index = end + 3
            lines = raw.split("\n")
            if lines and lines[0].strip() == "":
                lines = lines[1:]
            indent = ""
            if lines:
                closing = lines[-1]
                indent = closing[: len(closing) - len(closing.lstrip())]
                lines = lines[:-1]
            def dedent(ln):
                if ln.startswith(indent):
                    return ln[len(indent):]
                # A short line that is all whitespace collapses to empty in Swift; a short line
                # with content is a compile error, so it can never reach us.
                return "" if ln.strip() == "" else ln

            joined = "\n".join(dedent(ln) for ln in lines)
            # A trailing backslash in a multi-line literal continues the line, as in source.
            while "\\\n" in joined:
                joined = joined.replace("\\\n", "")
            parts.append(joined)
        elif index < len(text) and text[index] == '"':
            index += 1
            out = []
            while index < len(text):
                ch = text[index]
                if ch == "\\":
                    nxt = text[index + 1] if index + 1 < len(text) else ""
                    if nxt == "(":
                        return None, index  # interpolated — not a static key
                    out.append({"n": "\n", "t": "\t", '"': '"', "\\": "\\", "0": "\0"}.get(nxt, nxt))
                    index += 2
                    continue
                if ch == '"':
                    index += 1
                    break
                out.append(ch)
                index += 1
            parts.append("".join(out))
        else:
            return None, index

        save = index
        while index < len(text) and text[index] in " \t\r\n":
            index += 1
        if index < len(text) and text[index] == "+":
            index += 1
            continue
        return "".join(parts), save


def keys_in(path):
    text = io.open(path, encoding="utf-8").read()
    found = []
    needle = "L10n.t("
    i = text.find(needle)
    while i != -1:
        value, _ = swift_string_literals(text, i + len(needle))
        if value:
            found.append(value)
        i = text.find(needle, i + len(needle))
    return found


def escape(value):
    return (value.replace("\\", "\\\\")
                 .replace('"', '\\"')
                 .replace("\n", "\\n")
                 .replace("\t", "\\t"))


def render():
    keys = set()
    for base, _, files in os.walk(SOURCES):
        for name in sorted(files):
            if name.endswith(".swift"):
                keys.update(keys_in(os.path.join(base, name)))
    body = "".join('"%s" = "%s";\n' % (escape(k), escape(k)) for k in sorted(keys))
    return HEADER + "\n" + body, len(keys)


def main():
    rendered, count = render()
    if "--check" in sys.argv:
        current = io.open(TABLE, encoding="utf-8").read()
        if current != rendered:
            print("en.lproj/Localizable.strings is out of date — run Scripts/extract-l10n-keys.py")
            return 1
        print("en.lproj/Localizable.strings is up to date (%d keys)" % count)
        return 0
    io.open(TABLE, "w", encoding="utf-8").write(rendered)
    print("wrote %d keys to %s" % (count, os.path.relpath(TABLE, ROOT)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
