import AppKit

@MainActor
final class ClipboardMonitor {
    /// The timer only exists while this is on: a 1.2 s wake-up for a feature that's off is pure cost.
    var isEnabled: Bool {
        didSet {
            guard isEnabled != oldValue, isStarted else { return }
            isEnabled ? scheduleTimer() : cancelTimer()
        }
    }

    private let onText: (String) -> Void
    private var timer: Timer?
    private var isStarted = false
    private var lastChangeCount: Int
    private var detecting = false

    /// nspasteboard.org markers: password managers flag secrets so clipboard tools leave them alone.
    static let privateMarkerTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    /// Reading the type list is metadata only; it never triggers the paste-privacy prompt.
    static func isPrivate(types: [NSPasteboard.PasteboardType]?) -> Bool {
        guard let types else { return false }
        return types.contains { privateMarkerTypes.contains($0) }
    }

    init(isEnabled: Bool, onText: @escaping (String) -> Void) {
        self.isEnabled = isEnabled
        self.onText = onText
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        isStarted = true
        if isEnabled { scheduleTimer() }
    }

    private func scheduleTimer() {
        guard timer == nil else { return }
        // Whatever was copied while monitoring was off is history, not a fresh copy to suggest.
        lastChangeCount = NSPasteboard.general.changeCount
        // Added in `.common` so it keeps firing while menus or sheets track the run loop; scheduledTimer registers only `.default`.
        let timer = Timer(timeInterval: 1.2, repeats: true) { [weak self] _ in
            // Bound here rather than `self?.` inside the Task: a capture list makes `self` a var, which older toolchains refuse to read from concurrent code.
            guard let self else { return }
            Task { @MainActor in self.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func cancelTimer() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        let count = pasteboard.changeCount
        guard count != lastChangeCount, !detecting else { return }
        lastChangeCount = count
        guard isEnabled, !Self.isPrivate(types: pasteboard.types) else { return }
        if #available(macOS 15.4, *), pasteboard.accessBehavior != .alwaysAllow {
            guard pasteboard.accessBehavior != .alwaysDeny else { return }
            // Ask first whether a link is there at all, so an ordinary copy never raises the
            // "Goel° would like to paste" prompt.
            detecting = true
            Task { @MainActor in
                defer { detecting = false }
                let found = (try? await pasteboard.detectedPatterns(for: [\.probableWebURL, \.links])) ?? []
                guard !found.isEmpty, pasteboard.changeCount == count else { return }
                readAndDeliver(pasteboard)
            }
            return
        }
        readAndDeliver(pasteboard)
    }

    private func readAndDeliver(_ pasteboard: NSPasteboard) {
        guard let text = pasteboard.string(forType: .string), !text.isEmpty else { return }
        onText(text)
    }
}
